services:
  - type: web
    name: autopost-instagram
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: INSTAGRAM_SESSION_ID
        sync: false
      - key: DRIVE_FOLDER_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: POST_TIMES
        value: "09:00,15:00,21:00"
      - key: TIMEZONE
        value: "America/Sao_Paulo"
      - key: PYTHON_VERSION
        value: "3.11"
